### ISSUE TITLE
NoMethodError: undefined method `mongo_session'

### ISSUE THREAD

**Issue by breiko83** [thinkwell/mongoid_nested_set#29]
I get this error every time I try to move a node to a child of another node.

`NoMethodError: undefined method`mongo_session' for Leaf:Class
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/bundler/gems/mongoid_nested_set-7f670b6caab5/lib/mongoid_nested_set/update.rb:128:in `block in move_to'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in`call'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in`_run_move_callbacks'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/mongoid-5.1.1/lib/mongoid/interceptable.rb:138:in`run_callbacks'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/bundler/gems/mongoid_nested_set-7f670b6caab5/lib/mongoid_nested_set/update.rb:78:in `move_to'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/bundler/gems/mongoid_nested_set-7f670b6caab5/lib/mongoid_nested_set/update.rb:31:in`move_to_child_of'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/bundler/gems/mongoid_nested_set-7f670b6caab5/lib/mongoid_nested_set/update.rb:61:in `move_to_new_parent'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in`block in make_lambda'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `call'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in`block in halting_and_conditional'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in`block in halting_and_conditional'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in`_run_callbacks'
... 18 levels...
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in`block in load'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in`load'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/commands/rails.rb:6:in `call'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/command_wrapper.rb:38:in`call'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/application.rb:183:in `block in serve'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/application.rb:156:in`fork'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/application.rb:156:in `serve'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/application.rb:131:in`block in run'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/application.rb:125:in `loop'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/application.rb:125:in`run'
    from /Users/carloschiesaro/.rvm/gems/ruby-2.2.0/gems/spring-1.6.1/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/carloschiesaro/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/carloschiesaro/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in`<main>'2.2.0 :017 > root.children << child`

**Comment by breiko83** [comment]
I see this gem is not working with mongoid 5.
I have moved to mongoid 4 and used @huacnlee fork and it now works.
