### ISSUE TITLE
move_to_child_of: NoMethodError: undefined method `update'

### ISSUE THREAD

**Issue by shimotori** [thinkwell/mongoid_nested_set#9]
I created a fresh rails app with Rails 3.2.3, Mongoid 3.0.0rc and mongoid_nested_set (9a7b5ab239a3).
When I try to move a node to a child of another, the following error occurred:

```
% r1 = Cat.create({name: 'root1'})
#<Cat _id: 4fe4182d85e8c1b827000001, _type: nil, lft: 1, rgt: 2, depth: 0, parent_id: nil, name: "root1">
% c1 = Cat.create({name: 'child1'})
#<Cat _id: 4fe4186d85e8c1b827000002, _type: nil, lft: 3, rgt: 4, depth: 0, parent_id: nil, name: "child1">
% c1.move_to_child_of r1
NoMethodError: undefined method `update' for #<Moped::Collection:0x3988ab8>
    from C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/mongoid_nested_set-9a7b5ab239a3/lib/mongoid_nested_set/update.rb:147:in `block (2 levels) in move_to'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongoid-3.0.0.rc/lib/mongoid/contextual/mongo.rb:131:in `block (2 levels) in each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/query.rb:78:in `block (2 levels) in each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/cursor.rb:26:in `block in each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/cursor.rb:26:in `each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/cursor.rb:26:in `each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/query.rb:77:in `each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/query.rb:77:in `block in each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/query.rb:76:in `tap'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/moped-1.0.0.rc/lib/moped/query.rb:76:in `each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongoid-3.0.0.rc/lib/mongoid/contextual/mongo.rb:130:in `block in each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongoid-3.0.0.rc/lib/mongoid/contextual/mongo.rb:516:in `selecting'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongoid-3.0.0.rc/lib/mongoid/contextual/mongo.rb:120:in `each'
    from C:in `each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/mongoid_nested_set-9a7b5ab239a3/lib/mongoid_nested_set/update.rb:131:in `block in move_to'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:403:in `_run__62807628__move__505168825__callbacks'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `__run_callback'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:385:in `_run_move_callbacks'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongoid-3.0.0.rc/lib/mongoid/callbacks.rb:95:in `run_callbacks'
    from C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/mongoid_nested_set-9a7b5ab239a3/lib/mongoid_nested_set/update.rb:78:in `move_to'
    from C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/mongoid_nested_set-9a7b5ab239a3/lib/mongoid_nested_set/update.rb:31:in `move_to_child_of'
    from (irb):7
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.3/lib/rails/commands/console.rb:47:in `start'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.3/lib/rails/commands/console.rb:8:in `start'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:41:in `<top (required)>'
    from S:/www/rsmongotree/script/rails:6:in `require'
    from S:/www/rsmongotree/script/rails:6:in `<top (required)>'
    from -e:1:in `load'
    from -e:1:in `<main>'
```

Also, the same error occurs on `r1.children << c1`.

`Cat` model is defined as follows:

``` ruby
class Cat
  include Mongoid::Document
  acts_as_nested_set
end
```

**Comment by shimotori** [comment]
I sent: [Pull Request #10: Fix "NoMethodError: undefined method `update'" error on move_to_child_of](https://github.com/thinkwell/mongoid_nested_set/pull/10).
